### ISSUE TITLE
jeesite2.0 跟jeesite有什么关系呢？有什么区别呢？

### ISSUE THREAD

**Issue by YaoZihuan** [smallyaohailu/jeesite#1]
jeesite2.0 跟jeesite有什么关系呢？有什么区别呢？
换作者了？

**Comment by smallyaohailu** [comment]
区别一:gem在公司，没法个人名义升级很多模块。现在的版本是以jeesite.net team名义发布的。
区别二:目前一期的计划是升级框架版本以及后台模板。
              二期集成微信。三期集成Android客户端接口。四期重新写工作流模块。
区别三:至于说换作者了，这个现在确实是我一个人升级，不过私下跟gem说过了，我做这个更侧重于商业尝试，商业模式成功了，就是team团队了，不成功就是各自版本了。毕竟2.0框架跟gem还不同，代码风格也很大。

**Comment by smallyaohailu** [comment]
还有现在是公有，等差不多是我这版本就是私有了。
代码书写更规范，数据库设计也更为规范，软件延展性，易用性有所提升，不过不要等我，项目比较多，每天能抽出来的时间非常的有限。
